# -*- coding: utf-8 -*-
"""duyguanalizi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_-119p341_FNfarhCC--KTzflXz85UPF

Duygu Analizi Çalışması

 Bu çalışma, ders kapsamında duygu analizi uygulamasını görmek amacıyla yapılmıştır.
Ders notlarında verilen Amazon uygulama yorumları veri seti üzerinde, cümlelerin
pozitif, negatif veya nötr olarak sınıflandırılması hedeflenmiştir.
 Bu amaçla:
 - NLTK kütüphaneleri kullanılmış,
 - VADER sentiment analyzer ile duygu skorları çıkarılmış,
 - Metin temizleme adımları uygulanmış,
 - TF-IDF vektörleştirme ve Logistic Regression modeli ile sınıflandırma denenmiştir.
"""

#kütüphane
!pip install nltk scikit-learn pandas

#nltk modülleri
import nltk
nltk.download("punkt")
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("vader_lexicon")

"""### 2. Veri Seti Hakkında Bilgi  
Bu çalışmada kullanılan veri seti, ders kapsamında sağlanan Amazon uygulama yorumlarından oluşmaktadır. Veri seti yaklaşık 43.000 cümle içermektedir. Yorumlar uygulama deneyimi, memnuniyet ve hata bildirimleri gibi farklı içeriklerden oluşmaktadır. Bu veri seti üzerinde duygu analizi yapılmıştır.

"""

from google.colab import files
uploaded = files.upload()

#dosya okuma
with open("duygu_analizi_amazon_veri_seti.csv", "r", encoding="utf-8", errors="ignore") as f:
    text = f.read()

print(text[:500])

"""### 3. Cümlelere Bölme İşlemi (Sentence Tokenization)
Veri setindeki metinler tek bir büyük metin halinde olduğu için, duygu analizi
yapabilmek amacıyla cümlelere ayrılmıştır. Bu adımda NLTK’nın `sent_tokenize`
fonksiyonu kullanılarak metin cümle bazında parçalanmış ve her bir cümle ayrı
bir analiz birimi haline getirilmiştir.

"""

#cümleleri ayırma(sentence tokenization)
from nltk.tokenize import sent_tokenize
import nltk
nltk.download('punkt_tab')

sentences = sent_tokenize(text)
len(sentences), sentences[:5]

"""### 4. VADER ile Duygu Skorlarının Hesaplanması
Bu aşamada her bir cümle için VADER duygu analiz modeli kullanılarak
compound duygu skorları hesaplanmıştır. VADER modeli, metinlerdeki
olumlu, olumsuz ve nötr ifadeleri analiz ederek -1 ile +1 arasında
bir skor üretir. Bu skor:
- +0.02 üzeri → Pozitif
- -0.05 altı → Negatif
- Aradaki değerler → Nötr
olarak sınıflandırılmıştır.

"""

#vader duygu analizi
from nltk.sentiment import SentimentIntensityAnalyzer
import pandas as pd

sia = SentimentIntensityAnalyzer()

results = []
for s in sentences:
    score = sia.polarity_scores(s)
    results.append({
        "sentence": s,
        "compound": score["compound"]
    })

df_sentiment = pd.DataFrame(results)
df_sentiment

#etiketleme(pozitif/negatif/nötr)
def label_sentiment(c):
    if c >= 0.02:          # eşik düşürüldü → daha fazla Positive çıkacak
        return "Positive"
    elif c <= -0.05:
        return "Negative"
    else:
        return "Neutral"

df_sentiment["label"] = df_sentiment["compound"].apply(label_sentiment)

"""### 5. Duygu Dağılımı Grafiğinin İncelenmesi
Bu grafikte, veri setindeki cümlelerin pozitif, negatif ve nötr olarak
dağılımı gösterilmektedir.

Grafik sonuçlarına göre:
- Pozitif cümleler büyük çoğunluktadır,
- Negatif cümlelerin sayısı daha düşüktür,
- Nötr cümleler ise orta seviyededir.

Bu durum, kullanıcı yorumlarının genel olarak olumlu bir eğilim taşıdığını
göstermektedir.

"""

#duygu dağılımı(pozitif / negatif / nötr)
import matplotlib.pyplot as plt

order = ["Positive", "Negative", "Neutral"]
colors = ["green", "red", "blue"]

df_ordered = df_sentiment["label"].value_counts().reindex(order, fill_value=0)

df_ordered.plot(kind="bar", color=colors)
plt.title("Duygu Dağılımı (Positive / Negative / Neutral)")
plt.xlabel("Duygu Sınıfı")
plt.ylabel("Cümle Sayısı")
plt.show()

"""### 6. Metin Temizleme (Preprocessing)
Duygu analizi modelinin daha doğru çalışabilmesi için metin üzerinde çeşitli
temizleme işlemleri uygulanmıştır. Bu adımda:

- Tüm metin küçük harfe dönüştürülmüş,
- Noktalama işaretleri ve özel karakterler kaldırılmış,
- `stopwords` olarak bilinen anlamsız bağlaç ve sık kullanılan kelimeler çıkarılmış,
- Kelimeler köklerine indirgenmiş (lemmatization).

Bu işlemler metnin daha sade hale gelmesini sağlayarak modelin performansını
arttırmayı amaçlamaktadır.

"""

#nlp temizliği(lowercase/stopwords/lemma)
 # LOWERCASE: Tüm metni küçük harfe çevirerek tutarlılık sağlar.
 #REMOVE PUNCTUATION & SPECIAL CHARACTERS:Harf ve boşluk dışındaki karakterleri temizler (noktalama, rakam, semboller).
 # TOKENIZATION: Metni kelimelere böler.
 # STOPWORDS REMOVAL:"the, is, and, of" gibi anlam taşımayan kelimeleri çıkarır.
 # LEMMATIZATION:Kelimeleri kök hâline indirger (cars → car, repairing → repair).

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
import re

stop_words = set(stopwords.words("english"))
lemma = WordNetLemmatizer()

def clean_text(t):
    t = t.lower()
    t = re.sub(r"[^a-zA-Z\s]", "", t)
    tokens = word_tokenize(t)
    tokens = [w for w in tokens if w not in stop_words]
    tokens = [lemma.lemmatize(w) for w in tokens]
    return " ".join(tokens)

df_sentiment["clean"] = df_sentiment["sentence"].apply(clean_text)
df_sentiment[["sentence", "clean", "label"]]

#CONFUSION MATRIX (Isı Haritası)
import seaborn as sns
import numpy as np
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# Re-define X, y, X_tfidf, X_train, X_test, y_train, y_test, model, y_pred for standalone execution
X = df_sentiment["clean"]
y = df_sentiment["label"]

tfidf = TfidfVectorizer(max_features=2000)
X_tfidf = tfidf.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf, y, test_size=0.3, random_state=42
)

model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
labels = sorted(y.unique())

plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d', cmap="Blues",
            xticklabels=labels, yticklabels=labels)
plt.xlabel("Tahmin Edilen")
plt.ylabel("Gerçek")
plt.title("Confusion Matrix")
plt.show()

#TF-IDF EN ÖNEMLİ KELİMELER (Feature Importance)
import numpy as np

feature_names = tfidf.get_feature_names_out()
coeffs = model.coef_[0]

# en önemli 20 kelime
top_indices = np.argsort(coeffs)[-20:]
top_features = feature_names[top_indices]
top_values = coeffs[top_indices]

plt.figure(figsize=(10,6))
plt.barh(top_features, top_values, color="purple")
plt.title("TF-IDF Modele Göre En Önemli Kelimeler")
plt.xlabel("Ağırlık (Coefficient)")
plt.show()

#kelime bulutu(word cloud)
!pip install wordcloud

"""### 7. Kelime Bulutu Analizi (WordCloud)

Bu bölümde temizlenmiş metinlerden oluşan bir kelime bulutu oluşturulmuştur.
Kelime bulutu, veri setinde en sık kullanılan kelimeleri görsel olarak
incelemeyi sağlar.

- Pozitif yorumlarda genellikle "great", "fun", "love", "app" gibi olumlu ve
  memnuniyet belirten kelimeler yoğunluk gösterir.
- Negatif yorumlarda "problem", "error", "freeze", "bug" gibi şikayet ve hata
  odaklı kelimeler öne çıkar.
- Nötr yorumlarda bağlamsal ve açıklayıcı kelimeler daha sık görülür.

Bu kelime bulutları, kullanıcı yorumlarının hangi temalar etrafında yoğunlaştığını görselleştirerek, duygu sınıflarının kelime tercihleri açısından farklılıklarını açıkça ortaya koymaktadır.
"""

from wordcloud import WordCloud
import matplotlib.pyplot as plt

# tüm temiz metinleri tek bir string haline getirelim
text_all = " ".join(df_sentiment["clean"])

# kelime bulutu oluştur
wordcloud = WordCloud(width=1200, height=700,
                      background_color="white",
                      colormap="viridis",
                      max_words=100).generate(text_all)

# görselleştir
plt.figure(figsize=(12, 6))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.title("Kelime Bulutu (Word Cloud)", fontsize=18)
plt.show()

#POZİTİF CÜMLELER KELİME BULUTU
from wordcloud import WordCloud
import matplotlib.pyplot as plt

positive_text = " ".join(df_sentiment[df_sentiment["label"] == "Positive"]["clean"])

if positive_text.strip():
    wordcloud_pos = WordCloud(width=1000, height=600, background_color="white").generate(positive_text)
    plt.figure(figsize=(12,6))
    plt.imshow(wordcloud_pos, interpolation="bilinear")
    plt.axis("off")
    plt.title("Pozitif Cümleler Kelime Bulutu")
    plt.show()
else:
    print("Pozitif kelime bulutu için yeterli veri yok.")

df_sentiment[df_sentiment["label"]=="Positive"][["sentence", "clean"]]

#“Negative” cümlelerden kelime bulutu
neg_text = " ".join(df_sentiment[df_sentiment["label"]=="Negative"]["clean"])
wordcloud = WordCloud(width=1200, height=700, background_color="white").generate(neg_text)

plt.figure(figsize=(12, 6))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.title("Negatif Cümleler Kelime Bulutu")
plt.show()

df_sentiment[df_sentiment["label"]=="Negative"][["sentence", "clean"]]

#Nötr kelime bulutu
neutral_text = " ".join(df_sentiment[df_sentiment["label"]=="Neutral"]["clean"])

wordcloud_neu = WordCloud(width=1000, height=600, background_color="white").generate(neutral_text)
plt.figure(figsize=(12,6))
plt.imshow(wordcloud_neu, interpolation="bilinear")
plt.axis("off")
plt.title("Neutral Sentences Word Cloud")
plt.show()

"""### 8. Model Performansının Değerlendirilmesi

Bu bölümde TF-IDF ile dönüştürülmüş metinler üzerinde Logistic Regression
modeli eğitilmiş ve modelin başarı düzeyi değerlendirilmiştir. Model çıktılarının
kalitesini analiz etmek için Confusion Matrix ve Classification Report
kullanılmıştır.

- **Confusion Matrix**, modelin doğru ve yanlış sınıflandırdığı örneklerin
  dağılımını gösterir. Bu matris, hangi sınıfların daha çok karıştırıldığını
  anlamaya yardımcı olur.

- **Classification Report**, her sınıf için Precision, Recall ve F1-Score
  metriklerini içerir.
  - *Precision*: Doğru pozitif tahmin yüzdesi
  - *Recall*: Gerçek pozitiflerin ne kadarının yakalandığı
  - *F1-Score*: Precision ve Recall’un dengeli bir ölçüsüdür

Bu metrikler, modelin pozitif–negatif–nötr duygu sınıflarındaki başarısını
karşılaştırmalı olarak değerlendirmeyi sağlar.

8.1 Confusion Matrix ve Sonuçların İncelenmesi
"""

#TF-IDF + Logistic Regression (Model Eğitimi)
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

X = df_sentiment["clean"]
y = df_sentiment["label"]

tfidf = TfidfVectorizer(max_features=2000)
X_tfidf = tfidf.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf, y, test_size=0.3, random_state=42
)

model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

"""8.1.1 Confusion Matrix Açıklaması

Confusion Matrix çıktısına göre: (%70 eğitim %30 test)

Pozitif sınıf, modelin en başarılı olduğu sınıftır (7255 doğru tahmin).

Nötr sınıf, yüksek doğruluk oranına sahiptir (2770 doğru tahmin).

Negatif sınıf, diğer sınıflarla en çok karışan sınıftır (Recall = 0.54).

Bu sonuçlar, modelin negatif yorumları ayırt etmede zorlandığını ancak pozitif ve nötr sınıflarda yüksek performans gösterdiğini ortaya koymaktadır.
"""

#TF-IDF + Logistic Regression (Model Eğitimi)
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

X = df_sentiment["clean"]
y = df_sentiment["label"]

tfidf = TfidfVectorizer(max_features=2000)
X_tfidf = tfidf.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf, y, test_size=0.2, random_state=42
)

model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

"""8.1.2 Confusion Matrix Açıklaması

Confusion Matrix çıktısına göre: (%80 eğitim, %20 test)

Pozitif sınıf, modelin en başarılı olduğu sınıftır (4841 doğru tahmin).

Nötr sınıf, yüksek doğruluk oranına sahiptir (1883 doğru tahmin).

Negatif sınıf, diğer sınıflarla en çok karışan sınıftır (Recall = 0.56).

Bu sonuçlar, modelin negatif yorumları ayırt etmede zorlandığını ancak pozitif ve nötr sınıflarda yüksek performans gösterdiğini ortaya koymaktadır.

## Logistic Regression – Değerlerin Kaynağı (%70 vs %80)

| Ölçüt / Değer            | **%70 Eğitim – %30 Test**          | **%80 Eğitim – %20 Test** |
|--------------------------|--------------------------------------------|----------------------------------------------------|
| **Accuracy**             | 0.86                      | 0.87                       |
| **Negatif Recall**       | 0.54                      | 0.56                       |
| **En İyi Sınıf**         | Pozitif, Nötr             | Pozitif, Nötr              |
| **En Zayıf Sınıf**       | Negatif                   | Negatif                    |
| **Negatif Tahmin Sorunu** | Daha belirgin            | Daha az belirgin           |
| **Genel Yorum**          | Test seti büyük → hata daha görünür | Eğitim fazla → başarı biraz artar |

8.2 LinearSVC, destek vektör makinelerinin doğrusal versiyonudur ve TF-IDF gibi yüksek boyutlu metin verilerinde çok güçlü performans gösterir.
Model, sınıflar arasındaki en iyi doğrusal ayrımı bulmayı amaçlar ve genellikle lojistik regresyondan daha yüksek f1-skoru üretir.
Bu nedenle metin sınıflandırma problemlerinde sık tercih edilen, hızlı ve etkili bir makine öğrenmesi yöntemidir.
"""

from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report, confusion_matrix

X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf, y, test_size=0.30, random_state=42
)

print("Eğitim veri sayısı:", X_train.shape[0])
print("Test veri sayısı:", X_test.shape[0])

svc_model = LinearSVC()
svc_model.fit(X_train, y_train)

svc_pred = svc_model.predict(X_test)

print("Linear SVC Confusion Matrix:\n", confusion_matrix(y_test, svc_pred))
print("\nLinear SVC Classification Report:\n", classification_report(y_test, svc_pred))

"""8.2.1 Linear SVC Confusion Matrix Açıklaması

(%70 eğitim – %30 test)

Confusion Matrix çıktısına göre Linear SVC modeli, özellikle pozitif ve nötr sınıflarda yüksek performans göstermektedir.

Pozitif sınıf, modelin en başarılı olduğu sınıftır (7263 doğru tahmin).
Nötr sınıf, yüksek doğruluk oranına sahiptir (2753 doğru tahmin).
Negatif sınıf ise diğer sınıflarla en çok karışan sınıftır (Recall = 0.57).

Bu sonuçlar, modelin negatif yorumları ayırt etmede zorlandığını ancak pozitif ve nötr yorumlarda oldukça güçlü performans sergilediğini göstermektedir.
"""

from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report, confusion_matrix

X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf, y, test_size=0.20, random_state=42
)

print("Eğitim veri sayısı:", X_train.shape[0])
print("Test veri sayısı:", X_test.shape[0])

svc_model = LinearSVC()
svc_model.fit(X_train, y_train)

svc_pred = svc_model.predict(X_test)


print("Linear SVC Confusion Matrix:\n", confusion_matrix(y_test, svc_pred))
print("\nLinear SVC Classification Report:\n", classification_report(y_test, svc_pred))

"""8.2.2 Linear SVC Confusion Matrix Açıklaması

(%80 eğitim – %20 test)

Confusion Matrix çıktısına göre Linear SVC modeli, özellikle pozitif ve nötr sınıflarda yüksek başarı göstermektedir.

Pozitif sınıf, modelin en başarılı olduğu sınıftır (4851 doğru tahmin).
Nötr sınıf, yüksek doğruluk oranına sahiptir (1868 doğru tahmin).
Negatif sınıf, diğer sınıflarla en çok karışan sınıftır (Recall = 0.59).

Bu sonuçlar, modelin negatif yorumları ayırt etmede hâlâ zorlandığını ancak pozitif ve nötr sınıflarda güçlü bir performans sergilediğini göstermektedir.

## Linear SVC – Değerlerin Kaynağı (%70 vs %80)

| Ölçüt / Değer            | %70 Eğitim – %30 Test      | %80 Eğitim – %20 Test      |
|--------------------------|-----------------------------|-----------------------------|
| **Accuracy**             | 0.87                        | 0.87                        |
| **Negatif Recall**       | 0.57                        | 0.59                        |
| **En İyi Sınıf**         | Pozitif, Nötr               | Pozitif, Nötr               |
| **En Zayıf Sınıf**       | Negatif                     | Negatif                     |
| **Negatif Tahmin Sorunu**| Daha belirgin               | Biraz daha az belirgin      |
| **Genel Yorum**          | Test büyük → hata görünür   | Eğitim fazla → negatif sınıf iyileşir |

8.3 Random Forest, birden fazla karar ağacının birlikte çalıştığı topluluk temelli (ensemble) bir makine öğrenmesi yöntemidir. Model, farklı ağaçlardan alınan tahminleri birleştirerek tek bir güçlü ve genelleştirilebilir sonuç üretir. TF-IDF gibi yüksek boyutlu metin verilerinde doğrusal olmayan ilişkileri yakalayabilmesi sayesinde metin sınıflandırma problemlerinde etkili bir alternatif olarak kullanılmaktadır. Bu nedenle Random Forest, çalışmada tercih edilen güçlü makine öğrenmesi yaklaşımlarından biridir.
"""

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# %70 eğitim - %30 test
X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf, y, test_size=0.30, random_state=42
)

print("Eğitim veri sayısı:", X_train.shape[0])
print("Test veri sayısı:", X_test.shape[0])

rf_model = RandomForestClassifier(n_estimators=300, random_state=42)
rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

print("Random Forest (%70-%30) Confusion Matrix:\n", confusion_matrix(y_test, rf_pred))
print("\nRandom Forest (%70-%30) Classification Report:\n", classification_report(y_test, rf_pred))

"""8.3.1 Random Forest Confusion Matrix Açıklaması

(%70 eğitim – %30 test)

Confusion Matrix çıktısına göre Random Forest modeli, pozitif ve nötr sınıflarda yüksek performans göstermektedir.

Pozitif sınıf, modelin en başarılı olduğu sınıftır (7325 doğru tahmin).
Nötr sınıf, yüksek doğruluk oranına sahiptir (2716 doğru tahmin).
Negatif sınıf ise diğer sınıflarla en çok karışan sınıftır (Recall = 0.48), model bu sınıfı ayırt etmekte zorlanmaktadır.

Bu sonuçlar, Random Forest modelinin negatif yorumları ayırt etmede sınırlı performans gösterdiğini ancak pozitif ve nötr sınıflarda güçlü tahminleme yaptığını ortaya koymaktadır.
"""

# %80 eğitim - %20 test
X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf, y, test_size=0.20, random_state=42
)

print("Eğitim veri sayısı:", X_train.shape[0])
print("Test veri sayısı:", X_test.shape[0])

rf_model = RandomForestClassifier(n_estimators=300, random_state=42)
rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

print("Random Forest (%80-%20) Confusion Matrix:\n", confusion_matrix(y_test, rf_pred))
print("\nRandom Forest (%80-%20) Classification Report:\n", classification_report(y_test, rf_pred))

"""8.3.2 Random Forest Confusion Matrix Açıklaması

(%80 eğitim – %20 test)

Confusion Matrix çıktısına göre Random Forest modeli, pozitif ve nötr yorumlarda yüksek performans göstermeye devam etmektedir.

Pozitif sınıf, modelin en başarılı tahmin ettiği sınıftır (4888 doğru tahmin).
Nötr sınıf, yüksek doğruluk oranını korumaktadır (1837 doğru tahmin).
Negatif sınıf ise diğer sınıflarla en çok karışan sınıf olmaya devam etmektedir (Recall = 0.52).

Bu sonuçlar, eğitim verisinin artırılmasının modeli genel olarak iyileştirdiğini, ancak negatif sınıfın hâlâ ayırt edilmesi en zor sınıf olduğunu göstermektedir.

## Random Forest – Değerlerin Kaynağı (%70 vs %80)

| Ölçüt / Değer            | %70 Eğitim – %30 Test | %80 Eğitim – %20 Test |
|--------------------------|------------------------|------------------------|
| **Accuracy**             | 0.86                   | 0.86                   |
| **Negatif Recall**       | 0.48                   | 0.52                   |
| **En İyi Sınıf**         | Pozitif                | Pozitif                |
| **En Zayıf Sınıf**       | Negatif                | Negatif                |
| **Negatif Tahmin Sorunu**| Daha belirgin          | Biraz daha az belirgin |
| **Genel Yorum**          | Test büyük → hatalar görünür | Eğitim fazla → negatif sınıf iyileşir |

8.4 Naive Bayes, olasılıksal temelli bir sınıflandırma yöntemidir ve özellikle metin sınıflandırma problemlerinde yüksek verimlilik sağlayan Multinomial Naive Bayes yaklaşımıyla bilinir. Model, kelime frekanslarını temel alarak sınıflar arasındaki olasılık dağılımını tahmin eder ve TF-IDF gibi özellik çıkarım yöntemleriyle birlikte hızlı ve etkili sonuçlar üretir. Basitlik, düşük hesaplama maliyeti ve büyük veri setlerinde yüksek performans sunması nedeniyle duygu analizi ve metin sınıflandırma çalışmalarında sık tercih edilen bir makine öğrenmesi yöntemidir.
"""

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, confusion_matrix

# %70 eğitim - %30 test
X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf, y, test_size=0.30, random_state=42
)

print("Eğitim veri sayısı:", X_train.shape[0])
print("Test veri sayısı:", X_test.shape[0])

nb_model = MultinomialNB()
nb_model.fit(X_train, y_train)

nb_pred = nb_model.predict(X_test)

print("Naive Bayes (%70-%30) Confusion Matrix:\n", confusion_matrix(y_test, nb_pred))
print("\nNaive Bayes (%70-%30) Classification Report:\n", classification_report(y_test, nb_pred))

"""8.4.1 Naive Bayes Confusion Matrix Açıklaması

(%70 eğitim – %30 test)

Confusion Matrix çıktısına göre Naive Bayes modeli, pozitif sınıfta yüksek recall değeriyle güçlü performans göstermesine rağmen negatif ve nötr sınıflarda belirgin zorluk yaşamaktadır.

Pozitif sınıf, modelin en başarılı tahmin ettiği sınıftır (7602 doğru tahmin, recall = 0.98).
Nötr sınıf, oldukça düşük bir recall değerine sahiptir (754 doğru tahmin, recall = 0.25).
Negatif sınıf ise en zayıf sınıf olup model tarafından sıklıkla yanlış sınıflandırılmıştır (541 doğru tahmin, recall = 0.25).

Bu sonuçlar, Naive Bayes modelinin pozitif yorumları güçlü şekilde ayırt ettiğini ancak negatif ve nötr sınıflarda sınırlı performans gösterdiğini ortaya koymaktadır.
"""

# %80 eğitim - %20 test
X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf, y, test_size=0.20, random_state=42
)

print("Eğitim veri sayısı:", X_train.shape[0])
print("Test veri sayısı:", X_test.shape[0])

nb_model = MultinomialNB()
nb_model.fit(X_train, y_train)

nb_pred = nb_model.predict(X_test)

print("Naive Bayes (%80-%20) Confusion Matrix:\n", confusion_matrix(y_test, nb_pred))
print("\nNaive Bayes (%80-%20) Classification Report:\n", classification_report(y_test, nb_pred))

"""8.4.2 Naive Bayes Confusion Matrix Açıklaması

(%80 eğitim – %20 test)

Confusion Matrix çıktısına göre Naive Bayes modeli, pozitif sınıfı oldukça başarılı bir şekilde tahmin etmeye devam ederken negatif ve nötr sınıflarda düşük performans göstermiştir.

Pozitif sınıf, modelin en güçlü tahmin ettiği sınıftır (5072 doğru tahmin, recall = 0.98).
Nötr sınıf, düşük recall değeri (0.25) nedeniyle model tarafından sıkça diğer sınıflarla karıştırılmıştır (518 doğru tahmin).
Negatif sınıf ise benzer şekilde düşük recall ile (389 doğru tahmin, recall = 0.28) modelin en zayıf performans gösterdiği sınıflardan biridir.

Bu sonuçlar, eğitim verisi arttığında modelin pozitif sınıf performansını koruduğunu ancak negatif ve nötr sınıflarda başarı artışının sınırlı kaldığını göstermektedir.

| **Ölçüt / Değer**         | **%70 Eğitim – %30 Test**    | **%80 Eğitim – %20 Test**                   |
| ------------------------- | ---------------------------- | ------------------------------------------- |
| **Accuracy**              | 0.69                         | 0.69                                        |
| **Negatif Recall**        | 0.25                         | 0.28                                        |
| **En İyi Sınıf**          | Pozitif                      | Pozitif                                     |
| **En Zayıf Sınıf**        | Negatif, Nötr                | Negatif, Nötr                               |
| **Negatif Tahmin Sorunu** | Çok belirgin                 | Biraz daha az belirgin                      |
| **Genel Yorum**           | Test büyük → hatalar görünür | Eğitim fazla → negatif sınıf hafif iyileşir |
"""

#Confusion Matrix Görselleştirme (Seaborn Heatmap)
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
labels = ["Negative", "Neutral", "Positive"]

plt.figure(figsize=(7,5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=labels, yticklabels=labels)

plt.xlabel("Tahmin Edilen")
plt.ylabel("Gerçek Değer")
plt.title("Confusion Matrix")
plt.show()

"""8.3 Precision – Recall – F1 Score Grafiği:

Bu grafik, modelin sınıflara göre precision, recall ve F1-score performans ölçümlerini karşılaştırmaktadır. Model pozitif ve nötr sınıflarda güçlü performans sergilerken negatif sınıfta başarı diğer sınıflara kıyasla daha düşüktür.
"""

#Precision – Recall – F1 Score Bar Chart (Sınıf Bazlı)

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred, output_dict=True)
classes = ["Negative", "Neutral", "Positive"]

precision = [report[c]["precision"] for c in classes]
recall = [report[c]["recall"] for c in classes]
f1 = [report[c]["f1-score"] for c in classes]

x = np.arange(len(classes))
width = 0.25

plt.figure(figsize=(10,6))
plt.bar(x - width, precision, width, label='Precision')
plt.bar(x, recall, width, label='Recall')
plt.bar(x + width, f1, width, label='F1-Score')

plt.xticks(x, classes)
plt.ylim(0, 1.0)
plt.title("Sınıf Bazlı Performans Metrikleri")
plt.ylabel("Skor")
plt.legend()
plt.show()

"""8.4 Sınıf Bazlı Performans Metrikleri (Precision–Recall–F1)

Negative sınıf: F1-Skor = 0.64 (model en çok bu sınıfta zorlanmıştır)

Neutral sınıf: F1-Skor = 0.86 (dengeli performans)

Positive sınıf: F1-Skor = 0.91 (en başarılı sınıf)

Genel doğruluk (Accuracy): %86
Bu oran, modelin genel olarak yüksek performans sergilediğini göstermektedir.
"""