# -*- coding: utf-8 -*-
"""Makinaogrn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vBIUsTcOpnMtC2gfvGyJgjUhiPEx3LLq
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
import os
from sklearn.model_selection import train_test_split

from google.colab import files
uploaded = files.upload()

"""# veri seti

"""

import os
print(os.listdir())
seker= pd.read_excel('sekerhastalıgı.xlsx')
seker.info()

eksik_veriler = seker.isnull().sum()
print(eksik_veriler)

numeric_cols = seker.select_dtypes(include=['number']).columns

# 3. IQR yöntemiyle aykırı değerleri sayın
outlier_summary = {}
for col in numeric_cols:
    Q1 = seker[col].quantile(0.25)
    Q3 = seker[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outlier_count = seker[(seker[col] < lower_bound) | (seker[col] > upper_bound)][col].count()
    outlier_summary[col] = outlier_count

# 4. Sonuçları DataFrame olarak gösterin
outlier_df = pd.DataFrame.from_dict(outlier_summary, orient='index', columns=['Aykırı Değer Sayısı'])
outlier_df.index.name = 'Kolon'
print(outlier_df)

numeric_cols = seker.select_dtypes(include=['number']).columns

# 3. IQR yöntemiyle aykırı değerlerin satır ve sütun konumlarını belirleyin
outlier_positions = []
for col in numeric_cols:
    Q1 = seker[col].quantile(0.25)
    Q3 = seker[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    # Aykırı değer maskesi
    mask = (seker[col] < lower) | (seker[col] > upper)

    # Aykırı değerlerin indeks ve değer bilgisini toplayın
    for idx in seker[mask].index:
        outlier_positions.append({
            'Satır İndeksi': idx,
            'Sütun': col,
            'Değer': seker.at[idx, col]
        })

# 4. Sonuçları DataFrame olarak görüntüleyin
outliers_df = pd.DataFrame(outlier_positions)
print(outliers_df)

numeric_cols = seker.select_dtypes(include=['number']).columns

# 3. IQR yöntemiyle aykırı değerlerin toplam sayısını hesaplayın
outlier_count = 0
for col in numeric_cols:
    Q1 = seker[col].quantile(0.25)
    Q3 = seker[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    # Aykırı değer maskesi ve sayımı
    mask = (seker[col] < lower) | (seker[col] > upper)
    outlier_count += mask.sum()

# 4. Sonucu ekrana yazdırın
print("Veri setindeki toplam aykırı değer sayısı:", outlier_count)

numeric_cols = seker.select_dtypes(include=['number']).columns

# 3. Her satır için tüm kolonlarda aykırı değer kontrolü yapıp temiz bir DataFrame oluşturun
mask = pd.Series(True, index=seker.index)
for col in numeric_cols:
    Q1 = seker[col].quantile(0.25)
    Q3 = seker[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    # Aykırı değer değilse True
    mask &= seker[col].between(lower_bound, upper_bound)

# 4. Aykırı değerleri çıkarılmış veri seti
seker_no_outliers = seker[mask].reset_index(drop=True)

# 5. Sonuçları ekrana yazdırın
print(f"Orijinal satır sayısı: {len(seker)}")
print(f"Aykırı değerler çıkarıldıktan sonra satır sayısı: {len(seker_no_outliers)}")

numeric_cols = seker.select_dtypes(include=['number']).columns

# 3) IQR tabanlı aykırı değer filtresi oluşturun
mask = pd.Series(True, index=seker.index)
for col in numeric_cols:
    Q1 = seker[col].quantile(0.25)
    Q3 = seker[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    mask &= seker[col].between(lower, upper)

# 4) Aykırı değerleri çıkarılmış son veri seti
seker_no_outliers = seker[mask].reset_index(drop=True)

# 5) Son hali ekrana verin
print("Son veri seti boyutu:", seker_no_outliers.shape)
display(seker_no_outliers)  # Colab ortamında DataFrame'i görüntüler

for column in seker.select_dtypes(include='number').columns:
    min_val = seker[column].min()
    max_val = seker[column].max()
    print(f"{column}: Min = {min_val}, Max = {max_val}")

from sklearn.preprocessing import MinMaxScaler
import pandas as pd

# Sayısal sütunları seç (object olmayanlar)
numeric_columns = seker.select_dtypes(include='number').columns
scaler = MinMaxScaler()
seker[numeric_columns] = scaler.fit_transform(seker[numeric_columns])

sns.pairplot(seker)

print((seker).columns)

from sklearn.model_selection import train_test_split

x=seker.drop('Sonuç', axis=1)#sonuç dışındakileri x e aktar demek.
y=seker['Sonuç']
x=seker.drop('Sonuç', axis=1)#sonuç dışındakileri x e aktar demek.
y=seker['Sonuç']
seker['Sonuç'] = pd.Categorical(seker['Sonuç'])# sonuc kategorize eder.
y=seker['Sonuç']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3,random_state=1)

x_train

"""# LogisticRegression

"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report
from sklearn.metrics import accuracy_score
seker= pd.read_excel('sekerhastalıgı.xlsx')
model = LogisticRegression()
x=seker.drop('Sonuç', axis=1)#sonuç dışındakileri x e aktar demek.
y=seker['Sonuç']
x=seker.drop('Sonuç', axis=1)#sonuç dışındakileri x e aktar demek.
y=seker['Sonuç']
seker['Sonuç'] = pd.Categorical(seker['Sonuç'])# sonuc kategorize eder.
y=seker['Sonuç']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3,random_state=1)

y_train = y_train.astype(int)
model.fit(x_train, y_train)

y_pred=model.predict(x_test)
y_test = y_test.astype(int)
confusion_matrix(y_true=y_test, y_pred=y_pred)

print(classification_report(y_true=y_test,y_pred=y_pred))

print("doğruluk değeri:",accuracy_score(y_true=y_test,y_pred=y_pred))

"""# Lineer Regression"""

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
model = LinearRegression()
label_encoder = LabelEncoder()
y_train = y_train.astype(int)
y_test_encoded = label_encoder.fit_transform(y_test)

model.fit(x_train, y_train)

x=seker.drop('Sonuç', axis=1)
 y=seker['Sonuç']
 seker['Sonuç'] = pd.Categorical(seker['Sonuç'])
 x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

x_train

all_data = np.concatenate((y_train, y_test, y_pred))# label encoder yapmadım.yapınca doğruluk değeri sıfır oldu.dönüşüm olamdığı için bence

y_pred = model.predict(x_test)
y_pred_encoded = label_encoder.transform(y_pred.astype(int))#verideki sınıf etiketlerini sayısala dönüştürür.
print("doğruluk değeri:",accuracy_score(y_true=y_test,y_pred=y_pred_encoded))

"""
#Karar Ağaçları sınıflandırması

"""

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier#karar ağacaının sınıflndırması
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
seker = pd.read_excel('sekerhastalıgı.xlsx')
x=seker.drop('Sonuç', axis=1)
y=seker['Sonuç']
seker['Sonuç'] = pd.Categorical(seker['Sonuç'])
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

x_train

colunm_trans=make_column_transformer((StandardScaler(),seker.drop('Sonuç', axis=1)),(OneHotEncoder(),[]))#verisetimin içerisinde kategorik değişken olmadığı içim onehotencode çalışmıyor.sayısallaşacak değişken yok.
label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(y_train)

""":
  budamak:model=DecisionTreeClassifier(criterion='gini/entropy/',random_state=1)
  max_depth=2 budama değeri
  
"""

model=DecisionTreeClassifier(criterion='entropy',max_depth=5,random_state=1)

model.fit(x_train, y_train)

tahminler=model.predict(x_test)
model.score(x_train,y_train)

model.score(x_test,y_test)

label_encoder = LabelEncoder()
y_test_encoded = label_encoder.fit_transform(y_test)

accuracy = model.score(x_test, y_test_encoded)
confusion_matrix(y_true=y_test_encoded,y_pred=tahminler)

print(classification_report(y_true=y_test_encoded,y_pred=tahminler))

print("başarı:",accuracy_score(y_true=y_test_encoded,y_pred=tahminler))

"""#Ortalama Kare Hata Değeri"""

from sklearn.tree import DecisionTreeClassifier
seker = pd.read_excel('sekerhastalıgı.xlsx')
x=seker.drop('Sonuç', axis=1)
y=seker['Sonuç']
seker['Sonuç'] = pd.Categorical(seker['Sonuç'])
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)
model=DecisionTreeClassifier(max_depth=3,random_state=1)
model.fit(x_train, y_train)
tahminler=model.predict(x_test)

tahminler_ve_sonuclar=pd.DataFrame({'Gercek Değerler':y_test.values.reshape(-1,),
                                    'Tahminler':tahminler.reshape(-1)})
tahminler_ve_sonuclar.head()

sns.lineplot(data=tahminler_ve_sonuclar,markers=True)

from sklearn import metrics
HataDeğeri=metrics.mean_squared_error(y_test.values.reshape(-1,),tahminler.reshape(-1,))
print("Ortalama Kare Hatası:",HataDeğeri)

"""#Topluluk Öğrenmesi-Random Forest"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
seker = pd.read_excel('sekerhastalıgı.xlsx')
x=seker.drop('Sonuç', axis=1)
y=seker['Sonuç']
seker['Sonuç'] = pd.Categorical(seker['Sonuç'])
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)
rf_model=RandomForestClassifier(n_estimators=55,random_state=1)

rf_model.fit(x_train, y_train)

tahminler=rf_model.predict(x_test)
rf_model.score(x_train,y_train)

rf_model.score(x_test,y_test)

print("Karmaşıklık Matrisi:")
print(confusion_matrix(y_true=y_test,y_pred=tahminler))

print("Sınıflandırma Raporu:")
print(classification_report(y_true=y_test,y_pred=tahminler))

print("Doğruluk Değeri:",accuracy_score(y_true=y_test,y_pred=tahminler))

degerler = [10, 30, 50, 70, 90, 110, 130,150,170, 200]
basarilar = []

for i in degerler :
    rf = RandomForestClassifier(n_estimators=i, random_state=1)
    rf.fit(x_train, y_train)
    preds = rf.predict(x_test)
    basarilar.append(accuracy_score(y_true=y_test, y_pred=preds))
plt.plot(degerler,basarilar)

"""#KMeans

"""

seker = pd.read_excel('sekerhastalıgı.xlsx')
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

x=seker.iloc[:,[3,4]]
print(x)

wcss=[]
küme_sayısı_listesi=range(1,10)

for i in küme_sayısı_listesi:
  kmeans=KMeans(n_clusters=i,init='k-means++',max_iter=10,n_init=5,random_state=0)
  kmeans.fit(x) # Changed y_kmeans to kmeans
  wcss.append(kmeans.inertia_)
  print("Küme sayısı:", list(küme_sayısı_listesi))
print("WCSS değerleri:", wcss)

import matplotlib.pyplot as plt

plt.plot(küme_sayısı_listesi,wcss)
plt.title('küme sayısı belirlemek için dirsek yöntemi')
plt.xlabel('küme sayısı')
plt.ylabel('wcss')
plt.show()

kmeans = KMeans(n_clusters=4, init='k-means++', max_iter=300, n_init=10, random_state=0)
y_kmeans = kmeans.fit_predict(x)
plt.scatter(x[y_kmeans == 0].iloc[:, 0], x[y_kmeans == 0].iloc[:, 1], s=50, c='red', label='küme 1')
plt.scatter(x[y_kmeans == 1].iloc[:, 0], x[y_kmeans == 1].iloc[:, 1], s=50, c='blue', label='küme 2')
plt.scatter(x[y_kmeans == 2].iloc[:, 0], x[y_kmeans == 2].iloc[:, 1], s=50, c='green', label='küme 3')
plt.scatter(x[y_kmeans == 3].iloc[:, 0], x[y_kmeans == 3].iloc[:, 1], s=50, c='yellow', label='küme 4')


plt.title('KMeans ile 4 Küme')
plt.xlabel('VKİ')  # Assuming the first column is 'VKİ'
plt.ylabel('Diyabet Aile Öyküsü')  # Assuming the second column is 'Diyabet Aile Öyküsü'
plt.legend()

"""#üç boyutlu uygulama"""

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
seker = pd.read_excel('sekerhastalıgı.xlsx')
x=seker.iloc[:,[2,3,4]].values
x=seker.drop('Sonuç', axis=1)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)
wcss=[]
küme_sayısı_listesi=range(1,11)
for i in küme_sayısı_listesi:
  kmeans=KMeans(n_clusters=i,init='k-means++',max_iter=300,n_init=10,random_state=1)
  kmeans.fit(x)
  wcss.append(kmeans.inertia_)
  print("Küme sayısı:", list(küme_sayısı_listesi))
print("WCSS değerleri:", wcss)

plt.plot(küme_sayısı_listesi,wcss)
plt.title('küme sayısı belirlemek için dirsek yöntemi')
plt.xlabel('küme sayısı')
plt.ylabel('wcss')
plt.show()

kmeans=KMeans(n_clusters=6,init='k-means++',max_iter=300,n_init=10,random_state=1)
y_kmeans=kmeans.fit_predict(x)

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

ax.scatter(x.loc[y_kmeans == 0, 'Glukoz'], x.loc[y_kmeans == 0, 'Yaş'], x.loc[y_kmeans == 0, 'Insulin'], s=100, c='red', label='Küme 1')
ax.scatter(x.loc[y_kmeans == 1, 'Glukoz'], x.loc[y_kmeans == 1, 'Yaş'], x.loc[y_kmeans == 1, 'Insulin'], s=100, c='red', label='Küme 2')
ax.scatter(x.loc[y_kmeans == 2, 'Glukoz'], x.loc[y_kmeans == 2, 'Yaş'], x.loc[y_kmeans == 2, 'Insulin'], s=100, c='green', label='Küme 3')
ax.scatter(x.loc[y_kmeans == 3, 'Glukoz'], x.loc[y_kmeans == 3, 'Yaş'], x.loc[y_kmeans == 3, 'Insulin'], s=100, c='yellow', label='Küme 4')

ax.set_xlim(seker['Glukoz'].min(), seker['Glukoz'].max())
ax.set_ylim(seker['Yaş'].min(), seker['Yaş'].max())
ax.set_zlim(seker['Insulin'].min(), seker['Insulin'].max())
ax.set_title('3D Kümele')
ax.set_xlabel('Glukoz')
ax.set_ylabel('Yas')
ax.set_zlabel('insülin')
ax.legend()
plt.show()

true_labels = seker['Sonuç']

from collections import Counter

cluster_mapping = {}
for cluster in range(kmeans.n_clusters):
    labels_in_cluster = true_labels[y_kmeans == cluster]
    # Check if the cluster has any data points before accessing most_common
    if labels_in_cluster.empty:
        # Handle empty cluster, e.g., assign a default label or skip
        cluster_mapping[cluster] = -1  # Assign -1 for empty clusters
    else:
        most_common_label = Counter(labels_in_cluster).most_common(1)[0][0]
        cluster_mapping[cluster] = most_common_label


from sklearn.metrics import accuracy_score

mapped_predictions = [cluster_mapping[label] for label in y_kmeans]
accuracy = accuracy_score(true_labels, mapped_predictions)
print("KMeans Accuracy:", accuracy)

train_cluster_labels = kmeans.predict(x_train)
test_cluster_labels = kmeans.predict(x_test)

train_true_labels = y_train
cluster_mapping_train = {}
for cluster in range(kmeans.n_clusters):
    labels_in_cluster = train_true_labels[train_cluster_labels == cluster]
    if labels_in_cluster.empty:

        cluster_mapping_train[cluster] = -1
    else:
        most_common_label = Counter(labels_in_cluster).most_common(1)[0][0]
        cluster_mapping_train[cluster] = most_common_label
mapped_predictions_train = [cluster_mapping_train[label] for label in train_cluster_labels]
valid_indices_train = [i for i, label in enumerate(mapped_predictions_train) if label != -1]
accuracy_train = accuracy_score(y_train.iloc[valid_indices_train], [mapped_predictions_train[i] for i in valid_indices_train])
mapped_predictions_test = [cluster_mapping_train[label] for label in test_cluster_labels]
valid_indices_test = [i for i, label in enumerate(mapped_predictions_test) if label != -1]
accuracy_test = accuracy_score(y_test.iloc[valid_indices_test], [mapped_predictions_test[i] for i in valid_indices_test])

print("KMeans Accuracy (Egitim verisi):", accuracy_train, "\nKMeans Accuracy (Test verisi):", accuracy_test) #Added \n for newline

"""#Yapay sinir ağları"""

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
seker = pd.read_excel('sekerhastalıgı.xlsx')
scaler = StandardScaler()
opt=Adam(learning_rate=0.001)
x=seker.drop('Sonuç', axis=1)
y = seker['Sonuç']
x_scaled = scaler.fit_transform(x)
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.3,random_state=0)
x_train.shape

model = Sequential()
model.add(Dense(units=64, activation='relu', input_dim=x_train.shape[1])) # Input layer
model.add(Dense(units=32, activation='relu')) # Hidden layer
model.add(Dense(units=1, activation='sigmoid'))
model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

histrory=model.fit(x_train,y_train,epochs=100,batch_size=4)

import matplotlib.pyplot as plt
plt.plot(histrory.history['loss'])
plt.plot(histrory.history['accuracy'])
plt.ylim(0,1)
plt.show()

loss, accuracy = model.evaluate(x_test, y_test)
print(loss,accuracy)

y_head=model.predict(x_test)
th=0.7
y_pred_classes=(y_head>th).astype(int)
from sklearn.metrics import confusion_matrix,accuracy_score, classification_report
print('Accuracy Score:',accuracy_score(y_test,y_pred_classes))
print('classigration Report:\n',classification_report(y_test,y_pred_classes))
print('confusion Matrix:\n',confusion_matrix(y_test,y_pred_classes))

print("başarı:",accuracy_score(y_true=y_test_encoded,y_pred=tahminler))

import seaborn as sns
import matplotlib.pyplot as plt

# Korelasyon matrisini hesapla
correlation_matrix = seker.corr()

plt.figure(figsize=(6, 5))  # Grafik boyutu küçüldü
sns.heatmap(correlation_matrix, annot=True, fmt=".2f", cmap="coolwarm", square=True,
            annot_kws={"size": 8}, cbar_kws={"shrink": 0.8})  # Yazı ve renk çubuğu küçüldü
plt.title("Korelasyon Matrisi", fontsize=10)
plt.xticks(rotation=45, fontsize=8)
plt.yticks(fontsize=8)
plt.tight_layout()
plt.show()

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Assuming y_pred_classes from the neural network is your desired prediction
y_pred = y_pred_classes

# Calculate confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Visualize
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Sağlıklı", "Diyabetli"])
disp.plot(cmap="Blues", values_format="d")
plt.title("Karışıklık Matrisi")
plt.show()

y_prob = model.predict(x_test)

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import roc_auc_score

# 1. Veri setini yükle
# Dosya adını kendi ortamınıza göre düzenleyin (ör. 'sekerhastaligi.csv')
df = pd.read_excel('sekerhastalıgı.xlsx')

# 2. Özellik (X) ve hedef (y) değişkenlerini ayır
# Burada hedef sütununun adı 'Outcome' varsayılmıştır; dosyanız farklıysa ona göre düzenleyin
X = df.drop('Sonuç', axis=1)
y = df['Sonuç']

# 3. Eğitim/Test setlerine ayır (%85 eğitim, %15 test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.15, random_state=42, stratify=y
)

# 4. Modelleri tanımla ve eğit
logreg_model = LogisticRegression(max_iter=1000).fit(X_train, y_train)
dt_model     = DecisionTreeClassifier().fit(X_train, y_train)
rf_model     = RandomForestClassifier().fit(X_train, y_train)
nn_model     = MLPClassifier(hidden_layer_sizes=(8,4), max_iter=500).fit(X_train, y_train)

# 5. AUC skorlarını hesapla
models = {
    "Logistic Regression": logreg_model,
    "Decision Tree": dt_model,
    "Random Forest": rf_model,
    "Neural Network": nn_model
}

print("Modellerin AUC Değerleri:")
for name, model in models.items():
    if hasattr(model, "predict_proba"):
        y_probs = model.predict_proba(X_test)[:, 1]
    else:
        y_probs = model.decision_function(X_test)
    auc = roc_auc_score(y_test, y_probs)
    print(f"{name}: {auc:.2f}")